# This file should contain anything that is the same across all services.
# Anything declared here can be overridden by the service specific config files.
# This may be a great place to have default values that do not match the Spring Cloud etc opinionated defaults
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    healthcheck:
  	  enabled: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8011/eureka/, http://192.168.99.100:8012/eureka/, http://192.168.99.100:8013/eureka/